### ISSUE TITLE
RNN is necessary?

### ISSUE THREAD

**Issue by XiaoJiNu** [shashwat14/UnifiedPoseEstimation#1]
Hi, if I don't implement the RNN, does the code work？ I'm not familiary with RNN...

**Comment by shashwat14** [comment]
Yes, the code still works. You don't need to implement RNN. 

RNN makes the result a little bit better. For example, a single image may not be enough to tell if a person is closing or opening the bottle because the actions look very similar for a single image. RNN just helps in "collecting' multiple actions to refine the results.

**Comment by XiaoJiNu** [comment]
Thanks for you reply, your work is so great! I will try it

**Comment by shashwat14** [comment]
Thanks! Let me know if you face any issues
